services:
  - type: web
    name: fitp-web-monitor
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && playwright install chromium
    startCommand: python src/main.py
    envVars:
      NODE_VERSION: 20
      PYTHON_VERSION: 3.12.3